name: neural-nlp
channels:
- defaults
- anaconda
- pytorch
dependencies:
  - python>=3.6
  - keras
  - pytorch
  - tensorflow
  - numpy
  - torchvision
  - h5py
  - networkx
  - scikit-learn
  - matplotlib
  - jupyter
  - bazel
  - nltk
  - gensim
  - theano
  - pip:
    - git+https://github.com/dicarlolab/mkgu
    - pillow
    - llist
    - git+https://github.com/mschrimpf/skip-thoughts.git
    - git+https://github.com/mschrimpf/lm_1b.git
    - nbsvm
