name: decomposition
channels:
- defaults
- soumith
dependencies:
  - python>=3.6
  - keras
  - h5py
  - pip:
    - sklearn
#    - git+https://github.com/mschrimpf/DenseNet.git  # cannot be installed automatically because of missing setup.py. Instead, clone and copy manually to site-packages.
    - git+https://github.com/rcmalli/keras-squeezenet.git
