name: neural-nlp
channels:
- defaults
dependencies:
  - python>=3.6
  - tensorflow
  - numpy
  - matplotlib
  - seaborn
  - jupyter
  - nltk
  - gensim
  - theano
  - pip:
    - git+https://github.com/mschrimpf/brain-score.git@aeae86b
    - git+https://github.com/mschrimpf/result_caching.git@b310e99
    - pillow
    - llist
    - git+https://github.com/mschrimpf/skip-thoughts.git@7d46c14
    - git+https://github.com/mschrimpf/lm_1b.git@dd4061b
    - nbsvm
    - git+https://github.com/williamrainer/OpenNMT-py.git@cdc8f37  # TODO: replace pip torchtext with  pip install git+https://github.com/pytorch/text.gitCollecting git+https://github.com/pytorch/text.git
