name: neural-metrics
channels:
- defaults
- anaconda
- pytorch
dependencies:
  - python>=3.6
  - keras
  - pytorch
  - torchvision
  - h5py
  - networkx
  - scikit-learn
  - matplotlib
  - jupyter
  - pip:
    - git+https://github.com/dicarlolab/mkgu
    - git+https://github.com/mschrimpf/DenseNet.git
    - git+https://github.com/rcmalli/keras-squeezenet.git
    - pillow
    - llist
