name: neural-correlations
channels:
- defaults
- anaconda
- pytorch
dependencies:
  - python>=3.6
  - keras
  - pytorch
  - torchvision
  - h5py
  - scikit-learn
  - pip:
    - git+https://github.com/mschrimpf/DenseNet.git
    - git+https://github.com/rcmalli/keras-squeezenet.git
    - pillow
